トップページで課題内容を記述
yumemi-inc/ios-junior-engineer-codecheck-backend pull request #8
Opened 2022-12-15 16:42 UTC by el-hoshino

トップページで課題内容を表示させてみました

2022-12-15 17:10 UTC, el-hoshino commented
@novr とりあえずMarkdownのパースだけなんとかライブラリー見つけましたが、テーブルとかのパースがまだ正しくできないようなので、そこら辺はHTMLで直で書こうかなと思っています；
やりたいことはとりあえずこのPRで提出したように、バックエンドのトップページで課題を表示したいのですが、ここでAPI仕様書とかをうまく表示させられたらいいなという感じで、何かアドバイスとかもらえたら助かります！

2022-12-19 07:25 UTC, novr requested changes

2022-12-19 07:25 UTC, novr commented on Sources/EndPoint/Index.swift
> +    <h1>株式会社ゆめみ iOS 未経験者エンジニア向けコードチェック課題</h1>
htmlヘッダー入れましょう、文字化けします
Swift.cloudのキャッチアップできていないのでHTMLのレンダリングサポートがあるか不明なので、いったんcontent直書きでもいいかも
```
<!DOCTYPE html>
<html lang="ja">
<head>
<title>たいとる</title>
</head>
<body>
~
```
最後
```
</body>
</html>
```

2022-12-19 07:25 UTC, novr commented on Sources/EndPoint/Index.swift
> +    <h3>API 仕様</h3>
APIの説明部分はopenapiで書けばHTML生成できるのでやりますー

2022-12-19 08:57 UTC, el-hoshino commented
@novr head追加しましたー、ついでにText Encodingも入れましたー

2022-12-19 08:59 UTC, novr approved these changes
LGTM

2022-12-19 09:15 UTC, merged